##########################################################################
#                                                                        #
#                          Service Identity Part                         #
#               For Further information, please check README             #
#                                                                        #
##########################################################################

service:
  name: "micro"
  id: 105  # id is a number for this service and must be unique - If the problem is in choosing a number, for example with letters default number is 999
  baseURL: "/v1/"
  grpc:
    host: "localhost"
    port: ":8082"
    protocol: tcp
    tls: false
  http:
    host: "localhost"
    port: ":8080"
    requestTimeout: 32
  router:
    - method: /pb.Micro/SayHelloxx
      description: "for say hello to my master!"
      maxAllowedAnomaly: 50
      middlewares:
        - CheckSome
        - checkSome
        - middleware3
    - method: /pb.Micro/SayHello
      description: "for say hello to my master!"
      maxAllowedAnomaly: 50
      middlewares:
        - CheckSome
        - checkSome
        - Middleware3
    - method: /SayHello
      description: "for say hello to my master!"
      maxAllowedAnomaly: 50
      middlewares:
        - CheckSome
        - checkSome
        - middleware3
##########################################################################
#                                                                        #
#                         Server Config Part                             #
#       Please set the server parameters based on your own settings      #
#                                                                        #
##########################################################################

jaeger:
  hostPort: "localhost:6831"
  logSpans: true

redis:
  username: ""
  password: ""
  db: 0
  host: "localhost:6379"
  logger: ""

etcd:
  username: "ruserasdasdasd"
  password: "T0pS3cr3t"
  watchlist:
  endpoints:
    - http://localhost:2379

postgres:
  username: "admin"
  password: "password"
  host: "localhostlocalhost:5432"
  schema: "micro"

Nats:
  username: ""
  password: ""
  encoder: "json"
  auth: false
  allowReconnect: true
  maxReconnect: 50
  reconnectWait: 5
  timeout: 3
  endpoints:
    - "nats://localhost:4222"

jwt:
  secret: "xxxxxxxxxxxxx"

logstash:
  endpoint: "localhost:5000"
  timeout: 5 # second

cors: "*"
env: 3