version: "3.7"

services:
  # -----------------------------
  # micro service
  # -----------------------------
  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/go/src/application
    networks:
      - backend
    ports: 
      - 1222:8080
      - 1223:8082


  # -----------------------------
  # redis database
  # -----------------------------
  redis:
    hostname: redis
    image: redis
    networks:
      - backend

  # -----------------------------
  # redis UI
  # -----------------------------
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "9251:8081"
    networks:
      - backend
      - frontend

  # -----------------------------
  # nats message broker
  # -----------------------------
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - backend

  # -----------------------------
  # postgres database
  # -----------------------------
  postgres:
    image: postgres:13.3
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - psql-micro:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: micro
    networks:
      - backend
  #

# -----------------------------
# networks
# -----------------------------
networks:
  backend:
  frontend:

# -----------------------------
# volumes
# -----------------------------
volumes: 
  psql-micro:
    driver: local
  pgadmin:
    driver: local