version: "3.7"

services:
  # -----------------------------
  # micro service
  # -----------------------------
  micro:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/go/src/application
    networks:
      - backend
    depends_on:
      - jaeger
    ports: 
      - 1212:8080
      - 1213:8081

  # -----------------------------
  # jaeger servcie 
  # -----------------------------
  jaeger:
    image: jaegertracing/all-in-one:1.20
    ports:
      - "1214:6831/udp"
      - "1215:16686"
    networks:
      - backend
      - frontend

  # -----------------------------
  # etcd servcie 0
  # -----------------------------
  etcd0:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd0:2379
    ports:
      - 4379:2379
      - 4380:2380
    networks:
      - backend

  # -----------------------------
  # scope monitor
  # -----------------------------
  scope:
    image: weaveworks/scope:1.13.1
    hostname: weave-scope
    pid: "host"
    privileged: true
    ports:
      - "1250:4040"
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker"
      - "true"
    networks:
      - backend
      - frontend

  # -----------------------------
  # redis database
  # -----------------------------
  redis:
    hostname: redis
    image: redis
    networks:
      - backend

  # -----------------------------
  # redis UI
  # -----------------------------
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "9251:8081"
    networks:
      - backend
      - frontend
  
  # -----------------------------
  # nats message broker
  # -----------------------------
  nats:
    image: nats
    networks:
      - backend
   
  # -----------------------------
  # postgres database
  # -----------------------------
  postgres:
    image: postgres:13.3
    restart: unless-stopped
    volumes: 
      - psql-micro:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: micro
    networks: 
      - backend
   
  # -----------------------------
  # admin ui 
  # -----------------------------
  adminer:
    image: adminer
    ports:
      - 1200:8080
    networks: 
      - backend

# -----------------------------
# networks
# -----------------------------
networks:
  backend:
  frontend:

# -----------------------------
# volumes
# -----------------------------
volumes: 
  psql-micro:
    driver: local
  pgadmin:
    driver: local