// Code generated by MockGen. DO NOT EDIT.
// Source: logstash_dao.go

// Package mock_elk is a generated GoMock package.
package mock_elk

import (
	elk "micro/client/elk"
	config "micro/config"
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MocklogstashInterface is a mock of logstashInterface interface.
type MocklogstashInterface struct {
	ctrl     *gomock.Controller
	recorder *MocklogstashInterfaceMockRecorder
}

// MocklogstashInterfaceMockRecorder is the mock recorder for MocklogstashInterface.
type MocklogstashInterfaceMockRecorder struct {
	mock *MocklogstashInterface
}

// NewMocklogstashInterface creates a new mock instance.
func NewMocklogstashInterface(ctrl *gomock.Controller) *MocklogstashInterface {
	mock := &MocklogstashInterface{ctrl: ctrl}
	mock.recorder = &MocklogstashInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklogstashInterface) EXPECT() *MocklogstashInterfaceMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MocklogstashInterface) Connect(confs config.Config) (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", confs)
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MocklogstashInterfaceMockRecorder) Connect(confs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MocklogstashInterface)(nil).Connect), confs)
}

// Get mocks base method.
func (m *MocklogstashInterface) Get() elk.LogStash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(elk.LogStash)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MocklogstashInterfaceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocklogstashInterface)(nil).Get))
}

// GetConn mocks base method.
func (m *MocklogstashInterface) GetConn() (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConn")
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConn indicates an expected call of GetConn.
func (mr *MocklogstashInterfaceMockRecorder) GetConn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConn", reflect.TypeOf((*MocklogstashInterface)(nil).GetConn))
}

// Write mocks base method.
func (m *MocklogstashInterface) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MocklogstashInterfaceMockRecorder) Write(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MocklogstashInterface)(nil).Write), p)
}
