// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: product/service.proto

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SampleAPIClient is the client API for SampleAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SampleAPIClient interface {
	SampleEndpoint(ctx context.Context, in *SampleRequest, opts ...grpc.CallOption) (*SampleResponse, error)
}

type sampleAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleAPIClient(cc grpc.ClientConnInterface) SampleAPIClient {
	return &sampleAPIClient{cc}
}

func (c *sampleAPIClient) SampleEndpoint(ctx context.Context, in *SampleRequest, opts ...grpc.CallOption) (*SampleResponse, error) {
	out := new(SampleResponse)
	err := c.cc.Invoke(ctx, "/haf80.api.product.SampleAPI/SampleEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleAPIServer is the server API for SampleAPI service.
// All implementations must embed UnimplementedSampleAPIServer
// for forward compatibility
type SampleAPIServer interface {
	SampleEndpoint(context.Context, *SampleRequest) (*SampleResponse, error)
	mustEmbedUnimplementedSampleAPIServer()
}

// UnimplementedSampleAPIServer must be embedded to have forward compatible implementations.
type UnimplementedSampleAPIServer struct {
}

func (UnimplementedSampleAPIServer) SampleEndpoint(context.Context, *SampleRequest) (*SampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SampleEndpoint not implemented")
}
func (UnimplementedSampleAPIServer) mustEmbedUnimplementedSampleAPIServer() {}

// UnsafeSampleAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SampleAPIServer will
// result in compilation errors.
type UnsafeSampleAPIServer interface {
	mustEmbedUnimplementedSampleAPIServer()
}

func RegisterSampleAPIServer(s grpc.ServiceRegistrar, srv SampleAPIServer) {
	s.RegisterService(&SampleAPI_ServiceDesc, srv)
}

func _SampleAPI_SampleEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleAPIServer).SampleEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/haf80.api.product.SampleAPI/SampleEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleAPIServer).SampleEndpoint(ctx, req.(*SampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SampleAPI_ServiceDesc is the grpc.ServiceDesc for SampleAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SampleAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "haf80.api.product.SampleAPI",
	HandlerType: (*SampleAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SampleEndpoint",
			Handler:    _SampleAPI_SampleEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product/service.proto",
}
